# Generated by Django 5.0.3 on 2024-04-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
