# Generated by Django 5.0.3 on 2024-04-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0002_alter_reqeusted_money_status_transaction_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_history',
            name='rate',
            field=models.FloatField(default=1.0),
        ),
    ]
